### ISSUE TITLE
Release for latest master?

### ISSUE THREAD

**Issue by regexident** [boxtown/statrs#97]
Is there any chance to get the latest `master` with the updated `rand` dependency released?

The following code fails to compile with `0.10.0`, yet succeeds with current [`master`]( 79ea7fa):

```rust
extern crate rand;
extern crate statrs;

use rand::distributions::Distribution;
use statrs::distribution::Normal;

fn main() {
    let normal = Normal::new(0.0, 1.0).unwrap();
    let sample = normal.sample(&mut rand::thread_rng());
}
```

```
error[E0599]: no method named `sample` found for type `statrs::distribution::Normal` in the current scope
 --> examples/beacon.rs:9:25
  |
9 |     let sample = normal.sample(&mut rand::thread_rng());
  |                         ^^^^^^
  |
  = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
  |
4 | use rand::distributions::Distribution;
  |
```

**Comment by boxtown** [comment]
Let me check to see what's gone in since `0.10.0` but it shouldn't be a big deal to cut a `0.10.1` or something

**Comment by dhardy** [comment]
I don't think you have many requirements on `rand` beyond the `Distribution` trait? As such I recommend using a less specific designator of the Rand version, e.g. `>=0.5, <0.7`. I suspect this trait will also not have breaking changes in the 0.7 release (as long as you don't use the `sample_iter` method), though can't be certain.

**Comment by boxtown** [comment]
We probably don't need to pin to `0.6.3` specifically but I think for now pinning our dependency to `0.6` will be fine.

**Comment by boxtown** [comment]
Just cut a `0.11.0` with the `rand` dependency upgraded to `0.6`. Also includes an implementation of `InverseCDF` for the `Normal` distribution thanks to @Palladinium
